// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MAUIDevelopment.Model.Types
{
    public partial class artikal_dnevnik
    {
        public artikal_dnevnik()
        {
            Inverseid_relatedNavigation = new HashSet<artikal_dnevnik>();
        }

        public int id_dnevnik { get; set; }
        public int id_dokument { get; set; }
        public int id_artikal { get; set; }
        public short multiply { get; set; }
        public decimal kol { get; set; }
        public decimal cijena_nab { get; set; }
        public decimal? cijena_pro { get; set; }
        public byte? id_tarifa { get; set; }
        public decimal? vr_ztn { get; set; }
        public decimal? popust { get; set; }
        public int? id_related { get; set; }
        public string opis { get; set; }
        public string id_lot { get; set; }
        public string jedinica { get; set; }
        public byte? id_tarifa_default { get; set; }
        public decimal? kol_pom { get; set; }
        public decimal? duzina { get; set; }
        public decimal? sirina { get; set; }
        public decimal? visina { get; set; }
        public decimal? neto_tezina { get; set; }
        public decimal? bruto_tezina { get; set; }
        public string napomena { get; set; }
        public short? id_mjesto { get; set; }
        public decimal? cijena_val { get; set; }
        public decimal? popust_akc { get; set; }
        public decimal? cijena_pro2 { get; set; }

        public virtual artikal_dokument id_dokumentNavigation { get; set; }
        public virtual artikal_dnevnik id_relatedNavigation { get; set; }
        public virtual ICollection<artikal_dnevnik> Inverseid_relatedNavigation { get; set; }
    }
}