// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MAUIDevelopment.Model.Types
{
    public partial class artikal_vrsta
    {
        public string vrsta { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
        public byte? order { get; set; }
    }
}