// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MAUIDevelopment.Model.Types
{
    public partial class dokument_vrsta
    {
        public dokument_vrsta()
        {
            artikal_dokument = new HashSet<artikal_dokument>();
        }

        public byte id_vrsta { get; set; }
        public string naziv { get; set; }
        public string skraceni { get; set; }
        public string opis { get; set; }

        public virtual ICollection<artikal_dokument> artikal_dokument { get; set; }
    }
}