// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MAUIDevelopment.Model.Types
{
    public partial class fiscal_enu
    {
        public int id_enu { get; set; }
        public string broj { get; set; }
        public string broj_enu { get; set; }
        public string kod_poslovnog { get; set; }
        public string naziv { get; set; }
        public string kod_odrzavaoca { get; set; }
    }
}