// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MAUIDevelopment.Model.Types
{
    public partial class fiscal_dokument
    {
        public fiscal_dokument()
        {
            Inverseid_vezaNavigation = new HashSet<fiscal_dokument>();
            artikal_dokument = new HashSet<artikal_dokument>();
        }

        public int id_fiscal { get; set; }
        public string tip { get; set; }
        public int? broj { get; set; }
        public string ikof { get; set; }
        public string jikr { get; set; }
        public string json_response { get; set; }
        public string status_code { get; set; }
        public string status_text { get; set; }
        public int? id_veza { get; set; }
        public string opcode { get; set; }
        public bool? externi { get; set; }
        public string enu_br { get; set; }
        public Guid? guid { get; set; }
        public DateTime? issue_datetime { get; set; }

        public virtual fiscal_dokument id_vezaNavigation { get; set; }
        public virtual ICollection<fiscal_dokument> Inverseid_vezaNavigation { get; set; }
        public virtual ICollection<artikal_dokument> artikal_dokument { get; set; }
    }
}