// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MAUIDevelopment.Model.Types
{
    public partial class partner
    {
        public partner()
        {
            Inverseid_parentNavigation = new HashSet<partner>();
            artikal_dokument = new HashSet<artikal_dokument>();
        }

        public int id_partner { get; set; }
        public byte id_tip { get; set; }
        public bool is_foreign { get; set; }
        public string naziv { get; set; }
        public string maticni { get; set; }
        public string pdv { get; set; }
        public string grad { get; set; }
        public string adresa { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string kontakt { get; set; }
        public decimal rabat { get; set; }
        public short? rok_placanja { get; set; }
        public string id_cijenovnik { get; set; }
        public int? id_radnik { get; set; }
        public decimal? fin_limit { get; set; }
        public short? dob_rokpla { get; set; }
        public decimal? dob_finlim { get; set; }
        public string sifra { get; set; }
        public decimal? latitude { get; set; }
        public decimal? longitude { get; set; }
        public byte? id_n_cijenovnik { get; set; }
        public short? id_grupa { get; set; }
        public int? id_parent { get; set; }
        public string postanski_broj { get; set; }
        public byte? id_drzava { get; set; }
        public Guid? uid_partner { get; set; }
        public bool? is_active { get; set; }
        public decimal? provizija_procenat { get; set; }
        public string napomena { get; set; }
        public bool obustave_zbirno { get; set; }
        public DateTime? uid_created { get; set; }
        public DateTime? uid_updated { get; set; }
        public bool? uid_sync { get; set; }
        public DateTime? created { get; set; }
        public DateTime? updated { get; set; }
        public decimal? potrazivanje_limit { get; set; }
        public int? br_rata { get; set; }
        public byte? fiscal_idtype { get; set; }
        public string hod { get; set; }
        public string ulica_broj { get; set; }

        public virtual partner id_parentNavigation { get; set; }
        public virtual ICollection<partner> Inverseid_parentNavigation { get; set; }
        public virtual ICollection<artikal_dokument> artikal_dokument { get; set; }
    }
}